name: terraform destroy

on:
  workflow_dispatch:

env:
  AWS_REGION: eu-west-2

permissions:
  id-token: write
  contents: read

defaults:
  run:
    working-directory: infra

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::060501087561:role/GitHubActionsRole
        aws-region: eu-west-2
        role-duration-seconds: 7200

    - name: Set up terraform
      uses: hashicorp/setup-terraform@v3

    - name: terraform init
      run: terraform init -reconfigure
    
    - name: Terraform destroy plan
      run: terraform plan -destroy

    - name: Terraform destroy
      run: terraform destroy -auto-approve